RGS_Decisioning=file://C:\Users\schrammelb\OneDrive - Dun and Bradstreet\Downloads\swagger.yaml
Credit_Information_B2C=file://C:\Users\schrammelb\OneDrive - Dun and Bradstreet\Downloads\credit_persons.json
Credit_Information_B2B=file://C:\Users\schrammelb\OneDrive - Dun and Bradstreet\Downloads\credit_companies.json

# RGS_Decisioning=file://C:\Users\micro\Downloads\swagger.yaml