# RGS_Decisioning=file://C:\Users\schrammelb\OneDrive - Dun and Bradstreet\Downloads\swagger.yaml
# Credit_Information_B2C=file://C:\Users\schrammelb\OneDrive - Dun and Bradstreet\Downloads\credit_persons.json

RGS_Decisioning=file://C:\Users\micro\Downloads\swagger.yaml