STARTUP_WINDOW_WIDTH = 1600
STARTUP_WINDOW_HEIGHT = 800
STARTUP_WINDOW_TITLE = "API Viewer"
STARTUP_WINDOW_ICON = "icon.png"
STARTUP_WINDOW_X = 100
STARTUP_WINDOW_Y = 100
STARTUP_WINDOW_RESIZABLE = True

BASE_SPACE = 20

NO_MARGIN = 0, 0, 0, 0
